#!/bin/bash
###############################################################################
# generated by src/generate-scripts.sh
###############################################################################
# * Auto execute with this script with this command: bash <(curl -L {url-to-raw-file})
# inlined from src/data-variables.sh
fish_function_path="${HOME}/.config/fish/functions"
bash_config_file="${HOME}/.bashrc"
source_dir="${HOME}/src"
###############################################################################
# inlined from src/includes/ascii-art/ubuntu.sh
#
#           ..I$$$$$$$$$$$$$$..
#         .$$$$$$$$$$$$$$$$$$$$$.
#      ..$$$$$$$$$$$$$$$$$$$$$$$$$..
#     .$$$$$$$$$$$$$$$$$$$7...$$$$$$.
#    .$$$$$$$$$$$$$$$$$$$Z    .$$$$$$.
#   .$$$$$$$$$$$7..     .$.   .$$$$$$$=
#  .$$$$$$$$$$..$.       .$$$$$$$$$$$$$.
# .$$$$$$$$$Z.  ,$.7$$$Z.. ...~$$$$$$$$$.
# :$$$$$$$$I    7$$$$$$$$$$.   .$$$$$$$$$.
# $$$$$$$$$   .$$$$$$$$$$$$$.   7$$$$$$$$.
# $$$$$..$$. .$$$$$$$$$$$$$$$.  .$$$$$$$$.
# $$$7    .$ .$$$$$$$$$$$$$$$....$$$$$$$$~
# $$$+    .Z  $$$$$$$$$$$$$$$===?$$$$$$$$=
# $$$$$. +$. .$$$$$$$$$$$$$$$.  .$$$$$$$$.
# $$$$$$$$Z   .$$$$$$$$$$$$$.   +$$$$$$$$.
# +$$$$$$$$:   .$$$$$$$$$$$.   .$$$$$$$$$.
# .$$$$$$$$$+.  .$:$$$$$7.   ..$$$$$$$$$.
#  .$$$$$$$$$$ .$.       .Z$$$$$$$$$$$$=
#   ,$$$$$$$$$$$?.      .$.  ..$$$$$$$$
#    .$$$$$$$$$$$$$$$$$$$$    .$$$$$$?
#     .$$$$$$$$$$$$$$$$$$$... $$$$$$.
#      ..$$$$$$$$$$$$$$$$$$$$$$$$$?.
#         .$$$$$$$$$$$$$$$$$$$$$~.
#           ..$$$$$$$$$$$$$$$~.
#               ....~+~,...
#

###############################################################################
# inlined from src/includes/ubuntu/development-ubuntu.sh

###############################################################################
# inlined from src/includes/ubuntu/package-mgmt-ubuntu.sh
function add_package(){
  sudo apt-get -y install "$@"
}
function package_update(){
  sudo apt-get update
}
###############################################################################
# inlined from src/includes/ubuntu/preferences-ubuntu.sh
function postinstall.set_manjaro_preferences(){
  # ?
}
###############################################################################
# inlined from src/includes/ubuntu/vscode-ubuntu.sh
function install.visual_studio_code(){
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

  add_package apt-transport-https
  package_update
  add_package code # or code-insiders

  # add extension
  for ext in "${vscode_exts[@]}"; do
    add_vscode_ext $ext
  done
}
###############################################################################
#create a list of install functions to confirm
installs+=($(compgen -A function | grep "preinstall\."));
installs+=($(compgen -A function | grep "install\."));
installs+=($(compgen -A function | grep "postinstall\."));
#confirm each script with user
for f in "${installs[@]}"; do
  echo -n "$f [y/N]: "; read -e answer;
  if [ "$answer" == "y" ]; then
    confirmed_installs+=( "${f}" )
  fi
done
#execute each confirmed script
for c in "${confirmed_installs[@]}"; do
  echo -e "\e[48;5;4m\e[38;5;4m$(seq -s '-' 1 $(tput cols) | tr -d '[:digit:]')\e[0m"
  echo -e "\e[38;5;250m \e[38;5;4m ${c} \e[0m";
  echo -e;
  $c;
done