#USAGE: OUTPUT_FILE
function generate.stand_alone_file(){
  info "${1}"
  cat ./includes/headers/bash.sh > $1
  echo -e "# generated by src/generate-scripts.sh" >> $1
  cat ./includes/headers/direct-exec.sh >> $1
  for item in "${scripts[@]}"; do
    echo "# inlined from src/${item}" >> $1
    cat "./${item}" >> $1
    echo >> $1
    echo "###############################################################################" >> $1
  done
  cat ./includes/headers/footer.sh >> $1
}