# generated by src/generate-includes.sh

function install.bash-shell-aliases(){
  echo -e "function l(){
  builtin ls -CF
}" > ${bash_config_file}
  echo -e "function ls(){
  builtin ls -CF
}" > ${bash_config_file}
  echo -e "function ll(){
  builtin ls -lhA
}" > ${bash_config_file}
  echo -e "function lll(){
  builtin ls -lhFA | less
}" > ${bash_config_file}
  echo -e "function o(){
  builtin open .
}" > ${bash_config_file}
  echo -e "function c(){
  code .
}" > ${bash_config_file}
  echo -e "function cd..(){
  cd ..
}" > ${bash_config_file}
  echo -e "function ...(){
  cd ../../
}" > ${bash_config_file}
  echo -e "function ....(){
  cd ../../../
}" > ${bash_config_file}
  echo -e "function .....(){
  cd ../../../../
}" > ${bash_config_file}
}
