# generated by src/generate-includes.sh

function install.fish-git-aliases(){
  echo -e "function gs
  git status -sb --ignore-submodules
end" > ${fish_function_path}/gs.fish
  echo -e "function gd
  git diff
end" > ${fish_function_path}/gd.fish
  echo -e "function gaa
  git add --all
end" > ${fish_function_path}/gaa.fish
  echo -e "function gcm
  git commit -m
end" > ${fish_function_path}/gcm.fish
  echo -e "function gcma
  git commit -a -m
end" > ${fish_function_path}/gcma.fish
  echo -e "function gb
  git branch
end" > ${fish_function_path}/gb.fish
  echo -e "function gco
  git checkout
end" > ${fish_function_path}/gco.fish
  echo -e "function gcob
  git checkout -b
end" > ${fish_function_path}/gcob.fish
  echo -e "function gpff
  git pull --ff-only
end" > ${fish_function_path}/gpff.fish
  echo -e "function gmff
  git merge --ff-only
end" > ${fish_function_path}/gmff.fish
  echo -e "function gsize
  git count-objects -vH
end" > ${fish_function_path}/gsize.fish
  echo -e "function gremove
  git rm -r --cached .
end" > ${fish_function_path}/gremove.fish
  echo -e "function ghist
  git log --graph --max-count=100 --pretty=format:\"%C(green)%h%C(reset) | %C(yellow)%d%C(reset) %s %C(cyan)%an : %C(dim)%cr%C(reset)\" --abbrev-commit
end" > ${fish_function_path}/ghist.fish
}
