# generated by src/generate-includes.sh

function install.fish-git-workflow-cj(){
  echo -e "function cpush
  git push
end" > ${fish_function_path}/cpush.fish
  echo -e "function cpull
  git pull --rebase --prune
git submodule update --init --recursive
end" > ${fish_function_path}/cpull.fish
  echo -e "function cundo
  git reset HEAD~1 --mixed
end" > ${fish_function_path}/cundo.fish
  echo -e "function creset
  git add -A
git commit -qm 'CLEAN POINT'
git reset HEAD~1 --hard
git clean -f -d
end" > ${fish_function_path}/creset.fish
  echo -e "function cinit
  git init
gi osx >> .gitignore
echo \"# READ.ME\" >> README.md
gcommit \"Initial\"
if test -n \$argv
  gconnect \$repo_uri
  git push -u origin master
end
end" > ${fish_function_path}/cinit.fish
  echo -e "function cconnect
  git remote add origin \$argv
git remote -v
end" > ${fish_function_path}/cconnect.fish
  echo -e "function cbranch
  git checkout -b \$argv
end" > ${fish_function_path}/cbranch.fish
  echo -e "function ccommit
  git add -A
if test -n \"\$argv\"
      git commit -m \"\$argv\"
  else
      git commit -m \"WIP\"
  end
end" > ${fish_function_path}/ccommit.fish
  echo -e "function cmerge
  set merge_branch (git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
git checkout master
gpull
git rebase -i master
git merge \$merge_branch
end" > ${fish_function_path}/cmerge.fish
}
