# generated by src/generate-includes.sh

function install.git_global_aliases(){
  git config --global alias.s "status -sb --ignore-submodules"
  git config --global alias.d "diff"
  git config --global alias.aa "add --all"
  git config --global alias.cm "commit -m"
  git config --global alias.cma "commit -a -m"
  git config --global alias.b "branch"
  git config --global alias.co "checkout"
  git config --global alias.cob "checkout -b"
  git config --global alias.pff "pull --ff-only"
  git config --global alias.mff "merge --ff-only"
  git config --global alias.size "count-objects -vH"
  git config --global alias.remove "rm -r --cached ."
  git config --global alias.hist "log --graph --max-count=100 --pretty=format:\"%C(green)%h%C(reset) | %C(yellow)%d%C(reset) %s %C(cyan)%an : %C(dim)%cr%C(reset)\" --abbrev-commit"
}
